# Generated by Django 4.2.3 on 2023-07-25 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=500)),
                ('deadline', models.DateTimeField()),
                ('deadline_reached', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=500)),
                ('multiple_answer', models.BooleanField(default=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_questions', to='polls.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=255)),
                ('number_times_chosen', models.IntegerField(default=0)),
                ('all_or_none', models.BooleanField(default=False)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='polls.questions')),
            ],
        ),
        migrations.CreateModel(
            name='PollsMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_visits', models.IntegerField(default=0)),
                ('number_of_submits', models.IntegerField(default=0)),
                ('polls', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polls_metadata', to='polls.poll')),
            ],
            options={
                'ordering': ['number_of_submits', 'number_of_visits'],
                'indexes': [models.Index(fields=['number_of_submits', 'number_of_visits'], name='polls_polls_number__1ad408_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['created'], name='polls_poll_created_a594f2_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['deadline'], name='polls_poll_deadlin_8ed63e_idx'),
        ),
        migrations.AddIndex(
            model_name='answers',
            index=models.Index(fields=['answers'], name='polls_answe_answers_6023d4_idx'),
        ),
    ]
