# Generated by Django 4.2.3 on 2023-08-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondents',
            name='answers',
        ),
        migrations.AddField(
            model_name='respondents',
            name='answers',
            field=models.ManyToManyField(related_name='answer_chosen', to='polls.answers'),
        ),
    ]
