# Generated by Django 4.2.3 on 2023-07-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='poll',
            name='polls_poll_created_a594f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='poll',
            name='polls_poll_deadlin_8ed63e_idx',
        ),
    ]
