# Generated by Django 4.2.3 on 2023-08-04 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_alter_poll_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_chosen', to='polls.answers')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_answered', to='polls.poll')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_respondent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['respondent'],
                'indexes': [models.Index(fields=['poll'], name='polls_respo_poll_id_516001_idx')],
            },
        ),
    ]
